### ISSUE TITLE
Reading Headers

### ISSUE THREAD

**Issue by navyamehta** [uwcfm/CFM-HACK-2018#5]
I was trying to find how to read off the headers in the stock file "ABX.TO" etc. How can I read the stock names from the file?

**Comment by achen831008** [comment]
The stocks object looks like the following:
`{
       "ABX.TO": [...],
       "AEM.TO":[...],
       ...
}`

An object is like a dictionary in python, which consists data in key-value pairs.
Look into this [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys).
